### ISSUE TITLE
Using workflow in factory name

### ISSUE THREAD

**Issue by clay-mindoula** [thoughtbot/factory_bot#1313] opened 2019-07-01 15:00 UTC
### Steps to reproduce
Here is the problem class:
```Ruby
FactoryBot.define do
  factory :WorkflowStatus do
    name { Faker::Lorem.words(2).join(' ') }
    member_program_status { ReferenceDatum.datum_values('member_program_status').sample }
    display_order { 1 }
    max_days { Faker::Number.between(0, 14) }
    is_default { false }
    active { true }
    program
  end
end

```

To get this to work I had to add an alias to the class:

```Ruby
FactoryBot.define do
  factory :WorkflowStatus, aliases: [:wf_status] do
    name { Faker::Lorem.words(2).join(' ') }
    member_program_status { ReferenceDatum.datum_values('member_program_status').sample }
    display_order { 1 }
    max_days { Faker::Number.between(0, 14) }
    is_default { false }
    active { true }
    program
  end
end


>> >> FactoryBot.create(:wf_status)
=> #<WorkflowStatus id: 2, name: "consectetur aliquam", member_program_status: "mps_pending" ...
```

Even using :WorkFlowStatus as the model name caused problems, in this case I had to use an alias again: "aliases: [:workflow_status]  

Damn, this actually "fixes" it, having and alias of the same name:
```Ruby
 factory :WorkflowStatus, aliases: [:workflow_status] do
```

### Expected behavior

Create the workflow record

### Actual behavior
Rails Console:
```Ruby
>> FactoryBot.create(:workflow_status)
Traceback (most recent call last):
        1: from (irb):5
ArgumentError (Factory not registered: workflow_status)
>> 
```

### System configuration
**factory_bot version**:      factory_bot (4.8.2)
      activesupport (>= 3.0.0)
    factory_bot_rails (4.8.2)
      factory_bot (~> 4.8.2)
**rails version**: Rails 5.2.3 
**ruby version**: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]

**Comment by composerinteralia** [comment] 2019-07-12 02:25
With this factory:

```rb
FactoryBot.define do
  factory :WorkflowStatus
end
```

This error is expected:

```rb
>> FactoryBot.create(:workflow_status)
Traceback (most recent call last):
        1: from (irb):5
ArgumentError (Factory not registered: workflow_status)
>> 
```

because you registered a factory called `:WorkflowStatus` (camel case), rather than a factory called `:workflow_status` (snake case). To fix this, you can define the factory as:

```rb
FactoryBot.define do
  factory :WorkflowStatus
end
```

I am going to close this, since this is the expected behavior, but let me know if you have any more questions. Thanks!

**Closed by composerinteralia** 2019-07-12 02:25 UTC

**Comment by clay-mindoula** [comment] 2019-07-12 15:04
yes! thx.
