### ISSUE TITLE
table_name_prefix being ignored when class name is a string

### ISSUE THREAD

**Issue by rpbaptist** [thoughtbot/factory_bot#1374] opened 2020-03-16 11:41 UTC
Versions:

- factory_bot_rails: 5.1.1
- rails: 6.0.2
- rspec: 3.8.0

I have the following setup

```ruby
# app/models/orders.rb
module Orders
  class << self
    def table_name_prefix
      "orders_"
    end
  end
end

# app/models/orders/signature.rb
module Orders
  class Signature < ApplicationRecord
  end
end

# spec/factories/orders/signatures.rb
FactoryBot.define do
  factory :signature, class: Orders::Signature do
  end
end
```

This works. However, Rubocop now tells me to use a string to define the class name. I don't have a strong opinion, so I let Rubocop autofix it.

The factory now becomes:

```ruby
# spec/factories/orders/signatures.rb
FactoryBot.define do
  factory :signature, class: "Orders::Signature" do
  end
end
```

Now the table lookup in the factory starts failing;

```ruby
      ActiveRecord::StatementInvalid:
        Mysql2::Error: Table 'schema.signatures' doesn't exist
```

Instead of looking at table `schema.orders_signatures` it forgets to look at the prefix as set in the module by `table_name_prefix`.

**Comment by alextrueman** [comment] 2020-03-29 13:11
I can't reproduce this error, I have created the same setup but everything works as it should.
@rpbaptist May I ask you to re-check that what you put in your description exactly what you have on and be sure that the problem still exists after running `spring stop` command?

**Comment by composerinteralia** [comment] 2020-03-29 13:26
Also, if it is possible to provide either a reproduction sample app, or a reproduction script in this format: https://github.com/thoughtbot/factory_bot/blob/master/.github/REPRODUCTION_SCRIPT.rb that would be most helpful.

**Comment by composerinteralia** [comment] 2020-04-16 01:53
I'm going to close this issue since we aren't able to reproduce the error. Please feel free to reopen if you are able to provide a sample app that reproduces the error. Thanks!

**Closed by composerinteralia** 2020-04-16 01:53 UTC
Labels: pending-response

**Comment by olegykz** [comment] 2021-03-25 13:42
@composerinteralia I can confirm that the issue still actual (factory_bot 5.1.2, factory_bot_rails 5.1.1) - I'll try to play with reproduction script

**Comment by olegykz** [comment] 2021-03-25 16:30
Ok, [here](https://github.com/rails/rails/issues/21476) is the related issue with rails autoloading mechanism, so the topic doesn't have any relation to the `factory_bot` itself
