### ISSUE TITLE
KeyError: Trait not registered: "__method__"

### ISSUE THREAD

**Issue by cesarizu** [thoughtbot/factory_bot#1495] opened 2021-05-18 04:06 UTC
### Description

When upgrading `factory_bot_rails`, on an app that uses `mongoid`, from version 4 to newer versions, and running our test suite I get now the following error:

`KeyError: Trait not registered: "__method__"`

or with `factory_bot_rails` 6

`Trait not registered: "__method__" referenced within "survey" definition`

### Reproduction Steps

I haven't been able to reproduce this with a simple example. This is a very large application. When running through a debugger I see that `FactoryBot::DeclarationList@declarations` has multiple `FactoryBot::Declaration::Implicit` with `@name == :__method__` and no other declaration.

This is a snippet from the `survey` factory:

```ruby
FactoryBot.define do
  sequence :survey_name do |n|
    "Survey #{n}"
  end

  factory :survey, class: Surveys::FlashSurvey do
    name { 'Name' }
    account
    created_at { Time.now - 1.year }
    created_by

    trait :intro do
      intro { true }
    end
    
    factory :intro_survey, traits: %i[intro]
  end
end
```

There are more traits and factories but all look very similar.

### Expected behavior

I would expect this to work or to display some error message pointing to the actual problem.

### Actual behavior

The errors are displayed.

### System configuration
**factory_bot version**:  5.2.0 & 6.2.0
**rails version**:  5.2.3
**ruby version**: 2.7.2
**mongoid**: 7.0.13

**Comment by cesarizu** [comment] 2021-05-18 16:22
Just for reference, this is a working reproduction script that doesn't reproduce the error.
[factory_bot_mongoid_error.zip](https://github.com/thoughtbot/factory_bot/files/6502824/factory_bot_mongoid_error.zip)

**Comment by aledustet** [comment] 2021-06-04 16:30
We are not sure what's going on in the example as you mentioned that the reproduction script works correctly. Here are some more debug steps you can take:
- Run `bundle open factory_bot`
- Navigate to `lib/factory_bot/declaration/implicit.rb`
- Add 
``` ruby
`puts caller if name.to_s == '__method__'` as the first

**Comment by composerinteralia** [comment] 2021-09-10 01:18
I'm going to close this, since there hasn't been any activity and we're not able to reproduce it. If you are able to narrow in on where `__method__` is getting called and can share more information here we can reopen the issue.

**Closed by composerinteralia** 2021-09-10 01:18 UTC
Labels: bug
