### ISSUE TITLE
`create_list` sets the values in the block post-factum

### ISSUE THREAD

**Issue by pirj** [thoughtbot/factory_bot#1444] opened 2020-10-02 12:20 UTC
### Description

The model saved to the database ignores the attributes passed in the block.

https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#building-or-creating-multiple-records:
```ruby
twenty_somethings = build_list(:user, 10) do |user, i|
  user.date_of_birth = (20 + i).years.ago
end
```

I'd love to hack on it provided some guidance.

### Reproduction Steps

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "factory_bot", "~> 6.0"
  gem "activerecord"
  gem "sqlite3"
end

require "active_record"
require "factory_bot"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :views, force: true do |t|
    t.date :date
    t.integer :views
    t.index %i[date], name: "index_daily_views_on_date", unique: true # <= THIS IS IMPORTANT
  end
end

class View < ActiveRecord::Base
end

FactoryBot.define do
  factory :view do
    date { Date.today }
    views { rand(100..500) }
  end
end

class FactoryBotTest < Minitest::Test
  def test_factory_bot_build_list_works
    views = FactoryBot.build_list(:view, 2) do |view, i|
      view.date = Date.today - i
    end

    assert_equal views[0].date, Date.today
    assert_equal views[1].date, Date.today - 1
  end

  def test_factory_bot_create_list_fails
    views = FactoryBot.create_list(:view, 2) do |view, i|
      view.date = Date.today - i
    end

    assert_equal views[0].date, Date.today
    assert_equal views[1].date, Date.today - 1
  end
end
```

Without the uniqueness index the second test failure goes away. But it is deceiving:
```ruby
views[1] # => #<View:0x0000562cd2584198 id: 2, date: Thu, 01 Oct 2020, views: 116>
views[1].reload # => => #<View:0x0000562cd2584198 id: 2, date: Fri, 02 Oct 2020, views: 116>
```

Notice the `date` change after `reload`.

#### Workaround

```ruby
    views = FactoryBot.build_list(:view, 2) do |view, i|
      view.date = Date.today - i
    end
    views.map(&:save!)
```

### Expected behavior

`date` attribute should be persisted as set on the model.

### Actual behavior

`date` attribute diverged between the instantiated model and DB record.

### System configuration

**factory_bot version**:  5.2.0, 6.1.0
**rails version**: -  
**ruby version**: 2.5.7

**Comment by pirj** [comment] 2020-10-19 21:44
Is a pull request welcome?
Any hint on the best approach?

**Comment by NoahTheDuke** [comment] 2020-10-19 21:49
I don’t think this is a bug. The model is saved when it’s created and then it’s passed to the block. If you want to update the model in the block, call `save`

**Comment by pirj** [comment] 2020-10-19 22:58
@NoahTheDuke [this spec](https://github.com/thoughtbot/factory_bot/blob/0b53d28b4c1f2458a1c405bf883ed058a1986620/spec/acceptance/create_list_spec.rb#L41) uses `create_list` and doesn't use `save` (or rather better `save!`) inside the block:
```ruby
      FactoryBot.create_list(:post, 20, title: "The Listing of the Block") do |post|
        post.position = post.id
      end
```

To be fair, [originally this spec used `build_list`](https://github.com/thoughtbot/factory_bot/commit/488e42d77b40444222f36a9c02205613d1097bb6#diff-024969345ba085f3a5a2816cc46816bc4d8c8d286d08bf358138dc71d408f87aR45), and for `build_list` I totally agree with you that saving inside the block is a reasonable approach.

In certain situations, this approach is not applicable to `create_list` at all. Specifically, e.g. with a unique index or a uniqueness validation on the `position` column:
```ruby
      FactoryBot.create_list(:post, 20, title: "The Indexed Block") do |post, index|
        post.position = index
      end
```

Not to mention the overhead of saving the model twice: executing an extra UPDATE statement, and running validations twice, some of which may issue additional database queries, such as `validates ... unique: true`.

Additionally, [`create_list` delegates to `send(strategy, ..., &block)`](https://github.com/thoughtbot/factory_bot/blob/0b53d28b4c1f2458a1c405bf883ed058a1986620/lib/factory_bot/strategy_syntax_method_registrar.rb#L42], and that might mean that a regular `create` can be at risk of suffering from the same problem. Its behaviour [is not specified](https://github.com/thoughtbot/factory_bot/blob/0b53d28b4c1f2458a1c405bf883ed058a1986620/spec/acceptance/create_spec.rb#L120) for this case.
The same applies to `create_pair`, which doesn't have a spec with a block at all.

**Comment by NoahTheDuke** [comment] 2020-10-20 02:30
The [documentation](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#building-or-creating-multiple-records) is pretty clear on it, and given my knowledge of the internals of the library, the library is consistent with the documentation. `create` [calls save!](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#custom-methods-to-persist-objects) on the instance, which happens before it's [returned](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#using-factories), and `create_list` creates multiple records and then [returns them as an array](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#building-or-creating-multiple-records).

I don't know exactly how one would go about writing a [custom method to persist the objects](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#custom-methods-to-persist-objects) with the necessary index, but that's probably the method you'll want to take.

**Comment by pirj** [comment] 2020-10-20 09:14
@NoahTheDuke What specific part of the documentation you are referring to?

> In order to set different attributes for each factory, these methods may be passed a block, with the factory and the index as parameters

Can you please elaborate on "it" in "pretty clear on it"? I assume you are trying to point out that setting attributes in a block does not persist those assignements.

I couldn't find it being mentioned explicitly that the block that is passed "the return object" is evaluated before or after `save!`. Am I missing something?

To add to your point, there's this example in the documentation:
```ruby
# Passing a block to any of the methods above will yield the return object
create(:user) do |user|
  user.posts.create(attributes_for(:post))
end
```
This, given the `posts.user_id` foreign key is set to`NOT NULL` in the database, would fail to run if the block is called before `user` is persisted, breaking the `NOT NULL` database constraint.

On the other hand,

> To set the attributes for each of the factories, you can pass in a hash as you normally would.

```ruby
twenty_year_olds = build_list(:user, 25, date_of_birth: 20.years.ago)
```

and

> In order to set different attributes for each factory, these methods may be passed a block

There's no clarification that in case of passing a hash attributes are persisted, but when passing a block they are not.
That is the real source of confusion. I really hope that you understand my point.

I'm a long-time happy user of FactoryBot. But this time I've stumbled across a spec that uses `create_list` with a block with an index parameter, and it doesn't work as its author intended.

I don't mind adjusting the specs and the documentation to reflect that the current behavior is by design.
And, keeping in mind the case with `user.posts.create` inside a block, I don't have a good non-invasive solution to how to allow both apart from calling `save!` once again when the block returns, relying on the underlying ORM's lazyness.

@composerinteralia Do you mind to chime in?

**Comment by composerinteralia** [comment] 2020-10-20 09:31
Thanks for the issue. While I can see why this is a bit confusing, and the documentation and test coverage could probably be more clear, I agree with @NoahTheDuke that this is not a bug.

The block passed to any of the build strategies does less than you might expect it to. It is essentially a [shorthand for using `.tap`](https://github.com/thoughtbot/factory_bot/blob/6fc93fc19ece3c8504361ca3e983f3ed0bcf85d4/lib/factory_bot/factory.rb#L43), so:

```rb
    views = FactoryBot.create(:view) do |view|
      view.date = Date.today
    end
```

is equivalent to:

```rb
    views = FactoryBot.create(:view).tap do |view|
      view.date = Date.today
    end
```

By the time we get to the block, factory_bot is completely done building and persisting the object. It yields the end result to the block, so any changes at that point would need to be manually persisted (for example by calling `view.save!`).

The situation is roughly the same with the `_list` methods, although they are roughly a shorthand for `.each_with_index` rather than `.tap`:

```rb
    views = FactoryBot.create_list(:view, 2) do |view, i|
      view.date = Date.today - i
    end
```

is equivalent to:

```rb
    views = FactoryBot.create_list(:view, 2).each_with_index do |view, i|
      view.date = Date.today - i
    end
```

My gut tells me that changing this behavior so that the block is run prior to the [object being persisted](https://github.com/thoughtbot/factory_bot/blob/6fc93fc19ece3c8504361ca3e983f3ed0bcf85d4/lib/factory_bot/strategy/create.rb#L12) would be sort of complicated to do in a backwards compatible way, but I haven't actually tried to do it.

You have a few options for how to work around this:

1. `save!` each object manually as you go. As you mentioned, this results in saving each object twice, which is not ideal.

```rb
    views = FactoryBot.create_list(:view, 2) do |view, i|
      view.date = Date.today - i
      view.save!
    end
```

2. `save!` each object manually as you go, but use `build_list` instead of `create_list` to avoid saving each object twice:

```rb
    views = FactoryBot.build_list(:view, 2) do |view, i|
      view.date = Date.today - i
      view.save!
    end
```

3. Write a custom method to build the list:

```rb
def views
  Array.new(2) do |i|
    FactoryBot.create(:view, date: Date.today - i)
  end
end
```

OK, back to parental leave for now 👋

**Comment by pirj** [comment] 2020-10-20 19:20
Thanks, guys, it's all clear now.

> changing this behavior so that the block is run prior to the object being persisted would be sort of complicated to do in a backwards compatible way

No doubt about that.

Let me sleep on it, I may figure something out.

**Comment by composerinteralia** [comment] 2020-10-22 13:34
Yay! I'm glad it is clear now. Since this isn't bug, I'm going to close this issue for now. It may still be possible to modify this behavior, but I don't see it as a super high priority at the moment since there are other ways to get the desired behavior without modifying factory bot. Thank you for the issue!

**Closed by composerinteralia** 2020-10-22 13:34 UTC
Labels: bug

**Comment by pirj** [comment] 2020-11-03 08:42
Thinking out loud.

Passing a block to `create`/`create_pair`/`create_list` has the same effect as using `tap` on them, and is a syntax sugar.
`tap` is just a few keystrokes more.

To be able to set attributes on the created model and keep the ability to create associations on already persisted modules, it's possible to make a distinction between the two (passing a block and using `tap`). `tap` would allow creating associated models, and it would be yielded with a persisted model argument. While a block would be called before persisting and would allow setting attributes.

```
3.times.do
  create(:user) do |user| # this is called before persisting `user`
    user.created_at = rand(10).days.ago
  end
end

3.times do
  create(:user).tap do |user| # this is called after persisting `user`
    user.create_account
  end
end
```

As for rolling this out, a warning in a pre-5.0 version can be issued when the block is passed, saying that "Passing a block is about to change its behavior in the upcoming Factory Bot 5.0. It will be passed the model before it is saved".

It's trickier with `create_list`, since calling `tap` would yield the whole list instead of yielding persisted models one by one.
`each` would do what's needed, but it won't work on a singular `create`. So, that would make a difference, where `create` needs to be called with `tap`, while `create_pair`/`create_list` with `each` to be able to create their associations.

**Comment by ngouy** [comment] 2020-11-30 19:27
I agree it's not an issue, but it is indeed very confusing
For unaware people
```rb
create(:user) do |user|
   user.name = "Jake"
end

create_list(:user, 1) do |user|
   user.name = "Jake"
end
```
Can be misleading that the second one doesn't create a Jake user

And especially more when

```rb
build_stubbed_list(:user, 1) do |user|
   user.name = "Jake"
end
```
Is "creating" persisted a Jake user (fakely persisted in DB)

When you look at use cases and their respective output, it's legit to think there is an issue with `create_list`, at least in a user point of view

**Comment by pirj** [comment] 2020-11-30 19:32
> it can be misleading that the second one doesn't create a Jake user

`create` doesn't as well!
Sounds like a good job for a style guide and a cop, doesn't it?

**Comment by ngouy** [comment] 2020-11-30 19:37
> > it can be misleading that the second one doesn't create a Jake user
> 
> `create` doesn't as well!
> Sounds like a good job for a style guide and a cop, doesn't it?

Damn I get caught in my own explanations. All of this is indeed confusing. A cop would be very useful

Because after thinking about it it's very useful that create renders the already persisted instance (when you want to create has_many children instances)
