### ISSUE TITLE
factory_bot_rails stopped generating id (persisting objects) after rails 6 upgrade 

### ISSUE THREAD

**Issue by salimane** [thoughtbot/factory_bot#1357] opened 2019-11-18 16:14 UTC
# Steps to reproduce
Given the following factories:

```ruby
FactoryBot.define do
  factory :region do
    name { Faker::Address.state }
    iso { 'de' }
  end
end

a = FactoryBot.create :region
# a.id => nil
# a.created_at => nil
```
# Expected behavior
I would expect the object to have both id and created_at defined. 
# Actual behavior
id is nil, created_at is nil 

# System configuration
factory_bot_rails version: 5.1.1
rails version: 6.0.1
ruby version: 2.6.3

The above was working on rails 5.2. I then upgraded the app to Rails 6 and factory_bot_rails to 5.1.1 and factories stopped working.

Am I doing something wrong?

**Comment by composerinteralia** [comment] 2019-11-19 17:35
This isn't something I have seen before. Would you be able to provide a reproduction script in this format: https://github.com/thoughtbot/factory_bot/blob/master/.github/REPRODUCTION_SCRIPT.rb

**Comment by madkin10** [comment] 2019-11-25 16:25
@salimane Any progress on this? I am seeing the same issue when trying to upgrade from 5.2 to 6.

**Comment by salimane** [comment] 2019-11-25 16:47
@madkin10 I found out that it is not related to factory_bot. For some reason, saving a simple object with ActiveRecord 6, after the upgrade from 5.2, was returning true but id was still nil.

```ruby
>> r = Region.new(name: 'Region', iso: '.*')
=> #<Region id: nil, name: "Region", iso: ".*", country_id: nil, created_at: nil, updated_at: nil>
>> r.new_record?
=> nil
>> r.save!
   (2.0ms)  BEGIN /*application:Kermit*/
  Region Update (1.9ms)  UPDATE `regions` SET `regions`.`name` = 'Region', `regions`.`iso` = '.*', `regions`.`updated_at` = '2019-11-25 16:44:18' WHERE `regions`.`id` IS NULL /*application:Kermit*/
   (1.5ms)  COMMIT /*application:Kermit*/
=> true
>> r.id
=> nil
>>
```
Notice that the ``save!`` is doing an ``UPDATE`` query instead of an ``INSERT`` query

**Comment by composerinteralia** [comment] 2019-11-25 19:16
Since it sounds like this is a Rails issue rather than a factory_bot issue I am going to close it. Thanks!

**Closed by composerinteralia** 2019-11-25 19:16 UTC

**Comment by salimane** [comment] 2019-11-26 12:23
@madkin10 did you found something on your end?

**Comment by madkin10** [comment] 2019-12-03 21:11
@salimane We actually decided to abandon the effort to upgrade to rails 6. We were just getting into a circle of fixing error A and error B or C would appear. So we are planning to revisit this in a few weeks. At that point I will likely open more specific issue for each thing we find.

**Comment by dmitryv** [comment] 2020-06-18 21:28
@salimane , I had the same issue and found the protected_attributes_continued gem to be the root cause.

**Comment by thoughtafter** [comment] 2020-11-17 23:18
In case anyone else hits this thread and it using the protected_attributes_continued gem:

https://github.com/westonganger/protected_attributes_continued/pull/18

**Comment by Wusinho** [comment] 2021-10-30 15:29
Any updates?
![image](https://user-images.githubusercontent.com/67179149/139539490-040ec1ad-cc5e-47ad-ba65-dbc0b7487ff3.png)

**Comment by dmkash** [comment] 2021-11-02 17:27
@Wusinho `FactoryBot.build` doesn't persist the record to the database, so it would be expected for `id` to be `nil` in the screenshot provided.  `post.save` will persist the record to the database, which will create the `id` and timestamp values. Or `FactoryBot.create` could be used in the first line to build and then persist the record.

**Comment by suyog-shimpi** [comment] 2022-03-01 12:16
Any updated? I am facing same issue while upgrading rails version from 5.2 to 6.0.

**Comment by swapnilfuturism** [comment] 2022-05-03 08:55
I am also facing same issue after upgrading from rails 4.2 to 5.

**Comment by Kroeg93** [comment] 2022-06-07 08:27
Same problem after upgrading from rails 4.2 to 5
