### ISSUE TITLE
getting started link broken

### ISSUE THREAD

**Issue by adiakritos** [thoughtbot/factory_bot#1184] opened 2018-09-03 00:07 UTC
<img width="1475" alt="screen shot 2018-09-02 at 8 07 24 pm" src="https://user-images.githubusercontent.com/1653901/44962282-db06be80-aeeb-11e8-83f4-4fe9cccfa8b8.png">

**Comment by BerkhanBerkdemir** [comment] 2018-09-03 11:28
Duplicate of #1172

**Closed** 2018-09-03 13:28 UTC
