### ISSUE TITLE
initialize_with ignores last variable if it comes after hash

### ISSUE THREAD

**Issue by ThatGerber** [thoughtbot/factory_bot#988] opened 2017-02-07 00:45 UTC
When trying to call `create` with a new factory, and pass in a trait containing a separate initialization, it ignores the passed in values. It could be that I'm misunderstanding the inheritance aspect of traits or I'm setting up wrong, since I'm not working within a Rails app. But it's not passing through the correct arguments to the constructor.

Here's an example of the code needed to create the problem.

``` Ruby
# lib/some_class.rb

class SomeClass < AnotherClass
  def initialize(options = {}, do_the_thing = true)
    @option1 = options[:one] || 'Some Value'
    super(options) if do_the_thing
  end
end

# spec/factories/some_class.rb

FactoryGirl.define do
  factory :the_class, class: SomeClass do
    skip_create

    trait :with_defaults do
      initialize_with { new }
    end

    trait :skip_superclass do
      initialize_with { new({}, false) }
    end
  end
end

# spec/mylib/some_class_spec.rb

describe SomeClass do
  subject { create(:the_class, :with_defaults) }

  describe '.new' do
    context 'when initialized with nothing' do
      # do_the_thing == true
      it 'should do thing.'
    end

    context 'when initialized without triggering parent class' do
      it 'should not do thing.' do
        subject { create(:the_class, :skip_superclass) }        
        # do_the_thing == true, but it should be false
        expect(subject.parent_class_value).to eq nil
      end
    end
  end
end
```

Thanks.

**Comment by composerinteralia** [comment] 2017-09-29 23:02
I'm not able to reproduce this locally. The bug may we in `Another Class`, not shown here.

**Comment by composerinteralia** [comment] 2018-06-12 15:42
Closing for now. Feel free to reopen if you can provide the full implementation of `AnotherClass` so I can reproduce the behavior you describe. Thanks!

**Closed by composerinteralia** 2018-06-12 15:42 UTC
