### ISSUE TITLE
Callback / trait timing issue in 5.2

### ISSUE THREAD

**Issue by corroded** [thoughtbot/factory_bot#1405] opened 2020-06-08 04:48 UTC
### Description

TBH I am not sure if this is a FactoryBot issue, so if it isn't please close. I have also asked [here](https://github.com/thoughtbot/factory_bot/commit/0f4b404569efadc0305218215f759e014a3acc50#commitcomment-39685812) and @composerinteralia has already mentioned there should not be any issues but to open if there could be one.

 We have a top level trait like so:

```ruby
FactoryBot.define do
  trait :with_ref do
    with_ref { true }
  end

  trait :generate_ref do
    transient do
      with_ref { nil }
    end

    after(:create) do |record, evaluator|
      if evaluator.with_ref == true # do not create a ref if it's nil
        # generate random ref here
      elsif evaluator.with_ref.present?
        # create specific ref here: e.g. (create :my_record, with_ref: 'some-ref')
        record.create_ref(ref: evaluator.with_ref)
      end
    end
  end
end
```

This is mostly because most of our models have a polymorphic `ref` association:

```
class Post
  has_one :ref
end

class Author
  has_one :ref
end

class Ref
  belongs_to :target, polymorphic: true
end

# factories:

FactoryBot.define do
  factory :author, traits: %i[with_ref generate_ref] do
  end

  factory :post, traits: %i[with_ref generate_ref] do
    title { 'Title' }
    
    trait :approved do
      before(:create) do |p|
        author = create :author,  :with_ref
        p.author = author
      end
    end
  end
end
```

Now the tricky bit is that some factories have `before(:create)` callbacks (see post factory above) and I think the 5.2 changes has been *sort of* affected by this. I say sort of, because I'm on the fence on where the fault actually lies:

- We are using rspec and I think `let` syntax memoizes at the point of `before` create.
- I cannot reproduce it using the reproduction script because of this (the `let` thing)
- On that same vein, the problem ONLY happens in FactoryBot 5.2

I am still trying to somehow reproduce the entire thing at least to make sure, but just putting this forward now in hoping that MAYBE the problem is something simple I've overlooked. Rest assured, I am still making a gist or project to show the issue.

### Reproduction Steps

Again, I am still in the process of making it reproducible but currently just doing it in the console WORKS. It's the specs that fail but ONLY in 5.2. Here is a sample with comments:

```
RSpec.describe 'something' do
  let(:post) { create :post }
  let(:approved_post) { create :post, :approved }

  it 'does something' do
    expect(post.ref).to be_present
    expect(approved_post.ref).to be_present
  end
end
```

### Expected and Actual behavior

In 5.1, the above will both pass. In 5.2 `expect(approved_post.ref).to be_present` FAILS. From our investigations though, it seems that there is a clash between the before/after create callbacks and the `let` memoizes the post record BEFORE the ref is created. The solution is to reload like so:

`expect(approved_post.reload.ref).to be_present`

Again, there are a bit too many variables at play which is why I am still in the process of making a better reproduction script. Also, we have a LOT of specs failing because of this so adding `reload` to each of the specs that fail because of this sounds incorrect and the wrong way to go. Additionally, my current fix is to add the reload on the base module:

```
...
    after(:create) do |record, evaluator|
      if evaluator.with_ref == true # do not create a ref if it's nil
        # generate random ref here
        record.reload
      elsif evaluator.with_ref.present?
        # create specific ref here: e.g. (create :my_record, with_ref: 'some-ref')
        record.create_ref(ref: evaluator.with_ref)
        record.reload
      end
...
``` 

If there is a way to have these `traits` not be in the base module but available for all factories, I would also be keen to look into it as a solution. I initially tried creating a base factory but then that needs a backing table and at this point, the transient traits are more of a `mixin` for us since not all models have a ref associated to it.

### System configuration
**factory_bot version**: 5.2  
**rails version**: 5.2.4.3
**ruby version**: 2.6.5

Additional:
**rspec version**: 3.9.1

**Comment by composerinteralia** [comment] 2020-06-08 13:09
Thanks for the issue! If you are able to share a sample repo and let us know what commands to run in the console to get this behavior that would also be helpful.

**Comment by corroded** [comment] 2020-06-09 02:30
This is my initial pass: https://gist.github.com/corroded/7b00521285c310318253db637f3bf04b

I have swapped in rspec because I think it might be part of the issue but will update once it actually works!

**Comment by composerinteralia** [comment] 2020-06-15 15:30
Any luck getting a failing test case for this issue?

**Comment by corroded** [comment] 2020-06-22 09:50
I haven't had the chance again, but this is a closer representation of the problem: https://github.com/splitpayments/factorybot_52_demo. I'll try to somehow make it fail by the end of the week 🙏

**Comment by corroded** [comment] 2020-07-08 02:02
Just a quick update, have been busy but I might be able to get to this one in a week or two.

**Comment by composerinteralia** [comment] 2020-07-08 02:09
Thanks for the update. No rush. If this ends up being low priority for you, we can also close this issue for now and then reopen later on.

**Comment by composerinteralia** [comment] 2020-07-16 20:57
I played around the test script you provided (I got it running by adding `require 'rspec/autorun'`, and then added an expectation around approved posts, as described in your comments), but I could not get this failing on any version of factory_bot, so I am going to close the issue for now.

Not a whole lot changed between factory_bot 5.1.0 and 5.2.0, so I don't have any hunches about what this could be.  There are some known cases where reloading in an `after(:create)` is necessary (check out the recently updated [`has_many` documentation](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#has_many-associations)), but that wouldn't have changed from one version of factory_bot to the next.

I'm not sure how much you are upgrading, but I would recommend upgrading one library at a time if you aren't already doing that. That can help narrow down what the source of the error is. If you are already doing that, the next thing I would try is bumping the library one minor or even one patch version at a time. Again, that might help narrow down where the issue is coming from. If we knew that a specific commit in factory_bot introduced a bug for you, we might be able to reverse-engineer how to reproduce that failure and then fix it.

Thanks for your efforts here, and let me know if you get new information and want me to reopen this.

**Closed by composerinteralia** 2020-07-16 20:57 UTC
Labels: bug, pending-response

**Comment by corroded** [comment] 2020-07-17 00:07
Thank you for helping out as well! My investigations were halted because of priorities but I will keep at it. We do have dependabot - which is how we caught and isolated the issue. Just frustrating that I can't reproduce it in a sample app. Will ask to reopen once I have time for it. Thank you again for all the help!
