### ISSUE TITLE
Readme  GETTING_STARTED link invalid

### ISSUE THREAD

**Issue by casaper** [thoughtbot/factory_bot#1179] opened 2018-08-31 10:45 UTC
Seems the link [GETTING_STARTED](http://rubydoc.info/gems/factory_bot/file/GETTING_STARTED.md)
is not working...

**Comment by vbrazo** [comment] 2018-09-02 01:17
+1

**Comment by composerinteralia** [comment] 2018-09-02 21:02
Duplicate of https://github.com/thoughtbot/factory_bot/issues/1172

**Closed by composerinteralia** 2018-09-02 21:02 UTC
