### ISSUE TITLE
hstore value is not getting saved

### ISSUE THREAD

**Issue by imi-milaap** [thoughtbot/factory_bot#1370] opened 2020-02-10 03:14 UTC
In my factory `rule` is `hstore` type but when I access in spec/model getting always `{ }`.
gem version: `5.1.1`
```
FactoryBot.define do
  factory :promotion do
    category { "amount" }
    rule {{ quantity: 3, unit: Promotion::AMOUNT, value: 15 }}
    active { true }
  end
end

```

**Comment by composerinteralia** [comment] 2020-02-10 04:01
With that factory, `FactoryBot.create(:promotion)` is roughly equivalent to:

```rb
promotion = Promotion.new
promotion.category = "amount"
promotion.rule = { quantity: 3, unit: Promotion::AMOUNT, value: 15 }
promotion.active = true
promotion.save!
```

As a first step I would try that code and see if you are seeing the same issue. If you do still see the issue with that code, then it is not coming from factory_bot.

Otherwise, please provide a reproduction script similar to our [sample reproduction script](https://github.com/thoughtbot/factory_bot/blob/master/.github/REPRODUCTION_SCRIPT.rb).

Thanks!

**Comment by composerinteralia** [comment] 2020-04-05 03:35
Closing since there hasn't been any activity for a while

**Closed by composerinteralia** 2020-04-05 03:35 UTC
