### ISSUE TITLE
Transient support for initialize_with

### ISSUE THREAD

**Issue by dmitry** [thoughtbot/factory_bot#1447] opened 2020-10-23 17:12 UTC
Add transient support for `initialize_with`.

### Problem this feature will solve

Currently it's not allowed to use transient attributes inside `initialize_with` block.

> This will build a hash of all attributes to be passed to new. It won't include transient attributes, but everything else defined in the factory will be passed (associations, evaluated sequences, etc.)

Solution will:

- allow to associate new or created objects from the outside of the factory build;
- as a result it will reduce duplicated code when you want to update model from the other (for example associated) record.

### Desired solution

```
factory :user do
  trait :admin do
    profile { build(:admin_profile) }

    transient do
      completed { false }
    end

    after(:build) do |record, evaluator|
      if evaluator.completed
        build(:admin_profile, :completed, record: record.profile) # pass record variable here, to refill it with required data
      end
    end
  end
end

factory :admin_profile do
  trait :with_phone_number do
    # attributes
  end
  trait :with_confirmed_email do
    # attributes
  end
  trait :with_identity_card do
    # attributes
  end

  trait :completed do
    with_phone_number
    with_confirmed_email
    with_identity_card
  end

  transient do
    record { nil }
  end

  # here is the trick
  initialize_with do |evaluator|
    instance = record&.new || new
    instance.attributes = **attributes
  end
end
```

To use it:

```
create(:user, :admin, :completed)
```

## Alternatives considered

Right now there are no solution that allows to add traits for the associations which was passed as an attribute to a `build` or `create` method. 

## Additional context

Might be good to have simpler solution, like controlling association`s attributes via traits = nested traits.

**Comment by entcheva** [comment] 2021-03-05 20:23
Hi @dmitry - would you be able to share a failing test that encompasses the functionality you're hoping for? Here's our [reproduction script](https://github.com/thoughtbot/factory_bot/blob/master/.github/REPRODUCTION_SCRIPT.rb) to help you get started. This will help us better understand the feature you're hoping to add.

**Comment by aledustet** [comment] 2021-11-05 15:39
Hi @dmitry trying to get a sense on what is the status of this issue. Where you able to get a reproduction script going? I am also curious in your use case, if the record is the value that needs to be passed in order to grab the attributes, could the attributes be spread right from the `after(:build)` block?

**Comment by dmitry** [comment] 2021-11-09 21:14
@aledustet I haven't worked on it anymore further, and can't remember why I wanted to implement it, but seems like it is somehow related to the following pattern:

```ruby
    trait :talent do
      after(:build) do |record, e|
        profile = e.profile_association.dup
        options = profile.extract_options!
        record.profile = build(
          :talent,
          *profile,
          **options.symbolize_keys
        )
      end
    end
```

Now you can do:

```ruby
         create(
            :user,
            :talent,
            profile_association: [
              :completed,
              agency: record.offer.provider
            ]
          ).profile
```

Simply it allows you to use traits and attributes for associations.

**Comment by composerinteralia** [comment] 2021-11-09 21:37
Using traits and attribute overrides on associations sounds like a slightly different issue (I think it has been discussed before, but I can't find where at the moment). There are some approaches to that involving transient attributes, but I don't think that relates to `initialize_with`.

I found https://github.com/thoughtbot/factory_bot/issues/1367, which might have been the original version of this issue (they have the same name). That issue was about whether the `attributes` method inside `initialize_with` should include transient attributes. The answer is that `attributes` should not include transient attributes. From the docs:

> Transient attributes are attributes only available within the factory definition, and not set on the object being built

So if you are setting them on the object being built, they should be regular attributes rather than transient attributes.

I'm going to close this issue, since I think transient attributes and `initialize_with` are working as designed.

**Closed by composerinteralia** 2021-11-09 21:37 UTC
Labels: feature
