### ISSUE TITLE
Add factory_trace as helpful tool in the doc

### ISSUE THREAD

**Issue by djezzzl** [thoughtbot/factory_bot#1296] opened 2019-05-06 17:50 UTC
Hi, thank you for the amazing gem `factory_bot`. I'm using that a lot! 

And because I'm using it a lot, sometimes, after a while, I forget which `factories` and `traits` are still in use and which are not. 

To automate the process of finding unused, I wrote a simple gem which helps me with that:
[factory_trace](https://github.com/djezzzl/factory_trace). 

It's super easy to integrate and use: 

```
$ FB_TRACE=1 rspec
total number of unique used factories & traits: 3
total number of unique unused factories & traits: 2
unused global trait with_email
unused factory admin
```

Moreover, it can deal with partial/parallel execution by collecting trace information from each piece and then process the outcome. 

```
# one part
FB_TRACE=trace_only FB_TRACE_FILE=fb_trace_result1.txt bundle exec rspec spec/first_spec.rb
# another part
FB_TRACE=trace_only FB_TRACE_FILE=fb_trace_result2.txt bundle exec rspec spec/second_spec.rb
# finally output the usage to the console
bundle exec factory_trace fb_trace_result1.txt fb_trace_result2.txt
# or to the file
FB_TRACE_FILE=fb_report.txt bundle exec factory_trace fb_trace_result1.txt fb_trace_result2.txt
```

By the help of the gem we removed around **15% (~90)** `factories` and `traits` from our codebase which makes the gem worth to have.

I'd be glad if you put the information about the gem somewhere in your docs that it can help people who uses the `factory_bot` too. 

Thank you in advance!

**Comment by composerinteralia** [comment] 2019-05-10 23:40
Nice work! I look forward to trying out the gem, and I am definitely open to listing some factory_bot-adjacent projects somewhere. We might even have something like that already in the wiki, but I fear most of the wiki is out of date.

**Comment by djezzzl** [comment] 2019-05-12 11:29
Hi @composerinteralia, thank you! 
I'd be glad if you share your opinion about the gem after a try.

I updated [Helpful Links](https://github.com/thoughtbot/factory_bot/wiki/Helpful-Links) section but as you said the wiki can be outdated I doubt many people check it. 

So I created a simple PR: https://github.com/thoughtbot/factory_bot/pull/1298 to put it under "Useful Tools" section in README. This way community will easily find it and, moreover, suggest their own tools to make experience with **Factory Bot** even better.

**Comment by composerinteralia** [comment] 2019-05-13 17:56
Thanks!

I just tried out the gem and it caught an unused factory and several unused traits. Nice work!

There was one bit of awkwardness with a trait that was used only by another trait. Here is an example of what that might look like:

```rb
FactoryBot.define do
  factory :user do
    trait :confirmed do
      confirmed_at { Date.current }
    end

    trait :finished_signup do
      confirmed
      finished_signup_at { Date.current }
    end
  end
end

FactoryBot.build(:user, :finished_signup)
```

In this example factory_trace tells us that the `:confirmed` trait is unused. My assumption was that I would be able to just delete the `:confirmed` trait and all would be well. But since the `:finished_signup` trait was relying on the `:confirmed` trait, I instead needed to move `confirmed_at { Date.current }` into `:finished_signup` before deleting `:comfirmed`.

Do you think there is a way to differentiate between traits that are completely unused, and traits that are only referenced by other factories and traits?

**Comment by djezzzl** [comment] 2019-05-14 07:33
Hey @composerinteralia, 

Nice catch! Let me fix this case. IMO, we should just not output `confirmed` at all, because it's actually used, just not directly. 

We could tell developer could move the content of one trait to another but, IMHO, it will make well written traits messy and complex. WDYT?

Anyway, could you merge the PR: https://github.com/thoughtbot/factory_bot/pull/1298 to add link to the docs? I'll fix the bug ASAP.

**Comment by composerinteralia** [comment] 2019-05-17 17:50
Thanks @djezzzl 

> we should just not output confirmed at all, because it's actually used, just not directly.

Yeah, that makes sense to me

---

You may also be interested in https://github.com/thoughtbot/factory_bot/issues/1281 and the related PRs:

https://github.com/thoughtbot/factory_bot/pull/1297
https://github.com/thoughtbot/factory_bot/pull/1293
https://github.com/thoughtbot/factory_bot/pull/1293

I assume you are using some of these methods that we are thinking of as private methods. I think it is still fine for you to use them in your gem even though they will be in `FactoryBot::Internal` instead of `FactoryBot`. Although they won't be considered part of the public API, these are mostly stable methods that are unlikely to change again after we move them.

**Closed** 2019-05-17 17:50 UTC
Labels: attached PR, documentation

**Comment by djezzzl** [comment] 2019-05-19 13:02
Thank you, I'll look at the PRs.
