### ISSUE TITLE
Field with _id suffix returns nil when a similar is filled

### ISSUE THREAD

**Issue by wbotelhos** [thoughtbot/factory_bot#1417] opened 2020-06-29 02:27 UTC
### Description

When an enum attribute is populated, other similar attribute with suffix `_id` returns `nil`.

### Reproduction Steps

```rb
create_table "invoices", force: :cascade do |t|
  t.string "partner_id", null: false
  t.integer "partner", null: false
end
```

```rb
FactoryBot.define do
  factory :invoice do
    partner_id { 'partner_id' }
  end
end
```

When `partner` is given, it returns `nil`:

```rb
build(:invoice, partner: :danca).partner_id
=> nil
```

When `partner` is not given or it is into factory as default, returns normally:

```rb
build(:invoice).partner_id
=> "partner_id"
```

Declaring both returns `nil` too:

```rb
build(:invoice, partner: :danca, partner_id: 'partner_id').partner_id
=> nil
```

Just the prefixed works:

```rb
build(:invoice, partner_id: 'partner_id').partner_id
=> "partner_id"
```

### System configuration
**factory_bot version**:  6.0.2
**rails version**:  6.0.3.2
**ruby version**: 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]

**Comment by composerinteralia** [comment] 2020-06-29 13:59
Thanks for the issue. This is a duplicate of https://github.com/thoughtbot/factory_bot/issues/1142, so I am going to close this issue and continue tracking it over there.

**Closed by composerinteralia** 2020-06-29 13:59 UTC
Labels: bug
