### ISSUE TITLE
GETTING_STARTED bad URL

### ISSUE THREAD

**Issue by ClayShentrup** [thoughtbot/factory_bot#1186] opened 2018-09-05 01:16 UTC
https://www.rubydoc.info/gems/factory_bot/file/GETTING_STARTED.md
![image](https://user-images.githubusercontent.com/163883/45065532-922b4300-b06e-11e8-871e-133bfb5d6388.png)

should be
https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md

**Comment by composerinteralia** [comment] 2018-09-05 12:55
Duplicate of #1172 #1179 #1184 #1185. Will be fixed when I push out the next release. Thanks!

**Closed by composerinteralia** 2018-09-05 12:55 UTC
