### ISSUE TITLE
accepts_nested_attributes_for :parent and stack level too deep

### ISSUE THREAD

**Issue by dobrien501** [thoughtbot/factory_bot#971] opened 2016-12-05 16:22 UTC
Im upgrading an app from Rails ~4.0.13 to 4.1.14.1. Unfortunately FactoryGirl is raising stack level errors when we use factories with associations.

If Parent accepts nested attributes for Child, then the next time `save` is called on Parent, `SystemStackError` is raised

Example

```
Class Parent

has_one :child
accepts_nested_attributes_for :child

Class Child

belongs_to :parent
```

```
factory :parent
  description "looks after child"
end

factory :child
  age 5
  parent

```
```
parent = FactoryGirl.create :parent
child = FactoryGirl.create :child, parent: parent
parent.child.persisted => true
parent.save => true
child.save => SystemStackError: stack level too deep
```

Creating child via ActiveRecord and not FactoryGirl, fixes the save call, as does removing `accepts_nested_attributes_for`

I've found one workaround for FactoryGirl, which is to pass the parent to the factory child in a block

```
  FactoryGirl.create(:child) {|child| child.parent = parent }
```

But this would mean updating 100s of specs! And I still wouldn't know what the problem is.

Any ideas welcome!

**Comment by composerinteralia** [comment] 2018-10-28 01:15
I was not able to reproduce this. Since the issue was opened a long time ago, I'm going to close it for now. If you run into something like this again, or if you are able to recreate it with more recent versions of Rails and factory_bot, please feel free to reopen. Thanks!

**Closed by composerinteralia** 2018-10-28 01:15 UTC
