### ISSUE TITLE
undefined method - after upgraded factory_bot_rails

### ISSUE THREAD

**Issue by chabgood** [thoughtbot/factory_bot#1276] opened 2019-03-24 01:23 UTC
This worked before factory_girls_rails:
```
FactoryBot.define do
  factory :answer do

    trait :multiple_choice_answer do
      answer Faker::Hacker.say_something_smart
    end

    trait :true_false_answer do
      answer { ["true", "false"].sample }
    end

  	trait :correct do
  	  correct true
  	end

  	trait :incorrect do
  	  correct false
  	end

  	factory :correct_mc_answer, :traits => [:correct, :multiple_choice_answer]
  	factory :incorrect_mc_answer, :traits => [:incorrect, :multiple_choice_answer]
  	factory :correct_tf_answer, :traits => [:correct, :true_false_answer]
  	factory :incorrect_tf_answer, :traits => [:incorrect, :true_false_answer]
  end
end
```

this worked before factory_bot_rails?

```
/Users/chabgood/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/factory_bot-5.0.2/lib/factory_bot/definition_proxy.rb:97:in `method_missing': undefined method 'answer' in 'multiple_choice_answer' factory (NoMethodError)
	from /Users/chabgood/projects/nuvola_academy/spec/factories/answer.rb:5:in `block (3 levels) in <main>'
	from /Users/chabgood/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/factory_bot-5.0.2/lib/factory_bot/trait.rb:12:in `instance_eval'
	from /Users/chabgood/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/factory_bot-5.0.2/lib/factory_bot/trait.rb:12:in `initialize'
	from /Users/chabgood/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/factory_bot-5.0.2/lib/factory_bot/definition_proxy.rb:173:in `new'
	from /Users/chabgood/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/factory_bot-5.0.2/lib/factory_bot/definition_proxy.rb:173:in `trait'
	from /Users/chabgood/projects/nuvola_academy/spec/factories/answer.rb:4:in `block (2 levels) in <main>'
	from /Users/chabgood/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/factory_bot-5.0.2/lib/factory_bot/syntax/default.rb:18:in `instance_eval'
	from /Users/chabgood/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/factory_bot-5.0.2/lib/factory_bot/syntax/default.rb:18:in `factory'
	from /Users/chabgood/projects/nuvola_academy/spec/factories/answer.rb:2:in `block in <main>'
	from /Users/chabgood/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/factory_bot-5.0.2/lib/factory_bot/syntax/default.rb:49:in `instance_eval'
	from /Users/chabgood/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/factory_bot-5.0.2/lib/factory_bot/syntax/default.rb:49:in `run'
	from /Users/chabgood/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/factory_bot-5.0.2/lib/factory_bot/syntax/default.rb:7:in `define'
	from /Users/chabgood/projects/nuvola_academy/spec/factories/answer.rb:1:in `<main>'
```

**Comment by composerinteralia** [comment] 2019-03-24 04:03
See https://github.com/thoughtbot/factory_bot/issues/1272 and https://github.com/thoughtbot/factory_bot_rails/issues/313

**Comment by composerinteralia** [comment] 2019-03-24 16:51
I'm going to close this since I think it is a duplicate of those other issues. I'll keep those other issues open for others who may run into this. Thanks!

**Closed by composerinteralia** 2019-03-24 16:51 UTC
