### ISSUE TITLE
Unable to reassign factory attribute defined as a sequence

### ISSUE THREAD

**Issue by partydrone** [thoughtbot/factory_bot#1402] opened 2020-06-04 03:36 UTC
### Description

I'm trying to write a simple test that validates the presence of an `email` attribute defined as a sequence in the factory, but the assignment fails and the `email` attribute retains its value.

### Reproduction Steps

I have a factory that uses a sequence to set the email attribute on a user:

```ruby
FactoryBot.define do
  factory :user do
    first_name { 'John' }
    last_name { 'Doe' }
    sequence(:email) { |n| "#{first_name}.#{last_name}.#{n}@example.com".downcase }
    password { 'password' }
  end
end
```

I can't assign `email` to a new value in my test:

```ruby
require 'test_helper'
describe User do
  subject { build :user }

  it "must be a valid object" do
    _(subject).must_be :valid?
  end

  it "requires an email address" do
    subject.email = nil
    _(subject).wont_be :valid?
  end
end
```

### Expected behavior

Within the test, I expect the value of `subject.email` to be `nil` when the assertion is evaluated.

### Actual behavior

The value of `subject.email` is still the value assigned by the factory upon build (e.g., `john.doe.2@example.com`) when the assertion is evaluated. In a pry session, I see something similar to this:

```shell
> subject.email
# "john.doe.4@example.com"
> subject.email = nil
# nil
> subject.email
# "john.doe.4@example.com"
```

### System configuration
**factory_bot version**:  5.1.2
**rails version**:  4.2.11.1
**ruby version**: 2.4.9

**Comment by composerinteralia** [comment] 2020-06-04 17:18
Hm, that doesn't ring any bells for me. Once the object is built, I can't think of any reason why factory_bot would affect how later attributes get assigned. Can you provide a reproduction script in this format: https://github.com/thoughtbot/factory_bot/blob/master/.github/REPRODUCTION_SCRIPT.rb

**Comment by composerinteralia** [comment] 2020-06-11 03:14
I'm going to close this for now, since it is not something I can reproduce. But we can reopen it if you are able to provide a reproduction script. Thank you!

**Closed by composerinteralia** 2020-06-11 03:14 UTC
Labels: bug, pending-response

**Comment by partydrone** [comment] 2020-08-19 04:34
Turns out someone overrode the writer method (`def email=(value)`) that had a guard clause in it for `empty?` values.
