### ISSUE TITLE
`after(:build, &:some_method)` doesn't work on ruby 3.0

### ISSUE THREAD

**Issue by masarakki** [thoughtbot/factory_bot#1458] opened 2021-01-06 18:25 UTC
because of 

```
$ docker run -it ruby:2.7 ruby -e 'puts :upcase.to_proc.arity'                                    
-1
$ docker run -it ruby:3.0 ruby -e 'puts :upcase.to_proc.arity'                                
-2
```

and the code in `factory_bot/callback.rb`:

```
  def run(instance, evaluator)
      case block.arity
      when 1, -1 then syntax_runner.instance_exec(instance, &block)
      when 2 then syntax_runner.instance_exec(instance, evaluator, &block)
      else syntax_runner.instance_exec(&block)
      end
    end
```

this code doesn't work on ruby 3.0.0:

```
after(:build, &:some_method)
```

> Failure/Error: it { create :user }
>     
>     ArgumentError:
>       no receiver given
>     # <internal:kernel>:90:in `tap'
>     # ./spec/foo_spec.rb:4:in `block (2 levels) in <top (required)>'

its works well:

```
after(:build) { |x|  x.some_method } 
```

### System configuration
**factory_bot version**:  
**rails version**:  
**ruby version**:

**Comment by composerinteralia** [comment] 2021-01-13 13:51
We ran into something similar with https://github.com/thoughtbot/factory_bot/commit/37bc11d720e092bbfc015832f6ca3ef157f95e3e. You seem to have a pretty good sense of the problem. Any interest in exploring a PR with a test and adding `-2` as an arity that we can handle?

**Comment by martinsp** [comment] 2021-02-18 13:28
I had the same issue. But it looks like it's fixed in master in commit: 37bc11d as mentioned by @composerinteralia 

Changing factory_bot dependency in Gemfile to 

```ruby
gem 'factory_bot', git: 'https://github.com/thoughtbot/factory_bot.git', ref: '37bc11d720e092bbfc015832f6ca3ef157f95e3e'
```

and running bundle update factory_bot fixes the issue in tests when using ruby 3.0.

It looks like a new factory_bot release with a fix in 37bc11d would resolve the problem.

**Comment by katelovescode** [comment] 2021-04-22 01:56
```
49) businesses API behaves like it creates a record /api/v1/businesses post behaves like server error responses for wrong api version with parameters on the wrong api version when authenticated internal server error returns a 500 response
      Failure/Error: let!(:user) { create(:confirmed_user) }

      ArgumentError:
        no receiver given
      Shared Example Group: "server error responses for wrong api version with parameters" called from ./spec/support/shared_examples_api_request.rb:302
      Shared Example Group: "it creates a record" called from ./spec/requests/api/v1/businesses_spec.rb:25
      # /Users/katedonaldson/.rvm/gems/ruby-3.0.1@pieforproviders/gems/factory_bot-6.1.0/lib/factory_bot/callback.rb:14:in `instance_exec'
      # /Users/katedonaldson/.rvm/gems/ruby-3.0.1@pieforproviders/gems/factory_bot-6.1.0/lib/factory_bot/callback.rb:14:in `run'
      # /Users/katedonaldson/.rvm/gems/ruby-3.0.1@pieforproviders/gems/factory_bot-6.1.0/lib/factory_bot/callbacks_observer.rb:11:in `block in update'
      # /Users/katedonaldson/.rvm/gems/ruby-3.0.1@pieforproviders/gems/factory_bot-6.1.0/lib/factory_bot/callbacks_observer.rb:10:in `each'
      # /Users/katedonaldson/.rvm/gems/ruby-3.0.1@pieforproviders/gems/factory_bot-6.1.0/lib/factory_bot/callbacks_observer.rb:10:in `update'
      # /Users/katedonaldson/.rvm/gems/ruby-3.0.1@pieforproviders/gems/factory_bot-6.1.0/lib/factory_bot/evaluation.rb:24:in `notify'
      # /Users/katedonaldson/.rvm/gems/ruby-3.0.1@pieforproviders/gems/factory_bot-6.1.0/lib/factory_bot/strategy/create.rb:11:in `block in result'
      # <internal:kernel>:90:in `tap'
      # /Users/katedonaldson/.rvm/gems/ruby-3.0.1@pieforproviders/gems/factory_bot-6.1.0/lib/factory_bot/strategy/create.rb:9:in `result'
      # /Users/katedonaldson/.rvm/gems/ruby-3.0.1@pieforproviders/gems/factory_bot-6.1.0/lib/factory_bot/factory.rb:43:in `run'
      # /Users/katedonaldson/.rvm/gems/ruby-3.0.1@pieforproviders/gems/factory_bot-6.1.0/lib/factory_bot/factory_runner.rb:29:in `block in run'
      # /Users/katedonaldson/.rvm/gems/ruby-3.0.1@pieforproviders/gems/factory_bot-6.1.0/lib/factory_bot/factory_runner.rb:28:in `run'
      # /Users/katedonaldson/.rvm/gems/ruby-3.0.1@pieforproviders/gems/factory_bot-6.1.0/lib/factory_bot/strategy_syntax_method_registrar.rb:28:in `block in define_singular_strategy_method'
      # ./spec/requests/api/v1/businesses_spec.rb:6:in `block (2 levels) in <top (required)>'
```

I'm still getting this problem any time I define a let! in my specs with a create call from factorybot

**Comment by lowski** [comment] 2021-04-22 11:08
Seems like there is a difference in symbol-to-proc behavior between Ruby versions:

```ruby
# Ruby 3
:tap.to_proc.lambda? # true
```

```ruby
# Ruby 2
:tap.to_proc.lambda? # false
```

Which leads to different `arity` results.

**Comment by composerinteralia** [comment] 2021-04-22 11:42
^ yup, that's correct. It looks like I already fixed this in https://github.com/thoughtbot/factory_bot/commit/37bc11d720e092bbfc015832f6ca3ef157f95e3e, but we haven't sent out a release in a while. We'll try to get out a release soon. In the meantime it should be safe to point to that commit directly if you'd like to use `Symbol#to_proc` here.

Thank you!

**Closed by composerinteralia** 2021-04-22 11:42 UTC
Labels: bug

**Comment by mileslane** [comment] 2021-05-04 22:59
A new release would be greatly appreciated!

**Comment by composerinteralia** [comment] 2021-05-07 16:27
Released factory_bot 6.2.0, which should address this.

**Comment by composerinteralia** [comment] 2022-01-14 11:44
Could you open a separate issue and include steps to reproduce? We’ve fixed the original error reported here, but maybe there’s another similar error coming from somewhere.

**Comment by andregit1** [comment] 2022-01-15 02:39
thx for ur replay, i just submit new issue on github, hope can be solved as
soon as possible

**Comment by evolve2k** [comment] 2023-01-13 02:56
@andregit1  please link to your new issue from here, so the rest of us can follow along. Thx
