### ISSUE TITLE
Feature question: Boilerplate for enum traits

### ISSUE THREAD

**Issue by Epigene** [thoughtbot/factory_bot#1049] opened 2017-10-16 11:48 UTC
I work with Rails and encounter models with enum fields.

```rb
class Task
  enum status: {queued: 0, started: 1, finished: 2}
end
```

Then in factory I define traits for these statuses in a programmatic way
```rb
FactoryGirl.define do
  factory :task, class: 'Task' do
    Task.statuses.each do |k, _|
      trait(k) { status: k }
    end
  end
end
```

This allows me to do `build_stubbed(:task, :finished)`.

I want to simplify this process to be able to write

```rb
FactoryGirl.define do
  factory :task, class: 'Task' do
    define_enum_traits_for(:status)    
  end
end
```

How would I go about defining a `define_enum_traits_for` method that is accessible in `FactoryGirl.define` block in all factory files of a project?

I had a look at https://github.com/thoughtbot/factory_girl/issues/564 but that does not seem quite what I'm after.

**Comment by composerinteralia** [comment] 2019-02-03 22:32
@lancejjohnson and I took a first pass at this in https://github.com/thoughtbot/factory_bot/commit/03e9a87773465e20f2276bbf9677a0c5d1e63035, and I think it is definitely doable. @seanpdoyle and I had also discussed maybe defining these automatically by looking at the object's [`defined_enums`](https://github.com/rails/rails/blob/00f7dbab7590c6ffd188da186067eb269e11580f/activerecord/lib/active_record/enum.rb#L100).

**Comment by connorshea** [comment] 2019-03-12 17:37
This'd be great!

**Comment by eLod** [comment] 2019-05-02 01:08
it would be nice to be able to use it without the `enum` field type, e.g. with a provided set of values (so it would work with `:string` or even other column types): `traits_for_enum :status, %w[enabled locked whatever]`

**Comment by connorshea** [comment] 2019-05-04 17:53
I just ran into this problem again, I think?

So I have a `GamePurchase` model with an enum that can be used to show whether you've completed a game, like this:

```ruby
enum completion_status: {
  unplayed: 0,
  in_progress: 1,
  dropped: 2,
  completed: 3,
  fully_completed: 4,
  not_applicable: 5
}
```

And then I made a factory with a trait like so, to test randomized values when running the test suite:

```ruby
# spec/factories/game_purchases.rb
trait :completion_status do
  completion_status { rand(0..5) }
end
```

The problem is that, when I went to add a new option to the enum I forgot to update this trait, so the new option wasn't ever being used in the test suite.

Solving this issue wouldn't really solve my problem, but I'm wondering if there's a better option here, or if there's a way to solve both these problems at once? Sorry if this isn't the right place to ask this 🙇

**Comment by eLod** [comment] 2019-05-10 12:12
@composerinteralia what is the status on this? would you accept a pr onto your branch adding the modifications i proposed?

**Comment by composerinteralia** [comment] 2019-05-17 17:59
@eLod I haven't had time to work on this recently, and I am unlikely to have time in the next few weeks.

I have mixed feelings about opening this field up to accept a set of values, but it had crossed my mind. Seeing some code would definitely help make a decision. I don't have a could sense of how much complexity that would add. I could also imagine somebody wanting to pass a hash: `traits_for_enum :status, { enabled: 0, locked: 1, whatever: 2 }`.

I also still like the idea of defining these traits automatically for any Rails models with traits.

**Comment by eLod** [comment] 2019-05-17 19:24
@composerinteralia my main use case is generally `status` columns with string values, sometimes even with a dedicated table to hold the enumeration values (so it is easy to add/remove values via an admin interface without code modification). sometimes i don't control the database schema. because of these i don't really use Rails' `enum` field myself (it only supports integer values in the database), but i would benefit from the boilerplate (not needing to write all the traits for all the different enumeration values).

i don't have a problem supporting any enumerable (arrays and hashes) values passed and have some time to work on it if you agree. i can definitely look into defining these traits automatically for models with `enum`s (i guess you've meant that). my concern is rather i would only work on this if there is willingness to accept the feature in the end, it's not clear to me if the idea itself has support (i mean the enum traits, not the modifications i proposed specifically).

**Comment by composerinteralia** [comment] 2019-05-17 19:49
@eLod that makes sense to me. I definitely plan to get this feature in eventually, and would appreciate your help on it if you are willing.

**Comment by eLod** [comment] 2019-05-17 20:58
@composerinteralia sure, i don't have time on the weekend but i can look into it next week, will look around and comply my thoughts about how to go with the implementation and get back to yo. if you have anything else in mind not covered in this issue yet please add. thanks.

**Comment by eLod** [comment] 2019-05-20 16:21
@composerinteralia pushed an initial version, opened a pr, left some comments

**Comment by klyonrad** [comment] 2020-01-23 11:20
Will this be picked up for reviewing/merging in this year? Is there anything that blocks it. Would be an extremely awesome feature

> because of these i don't really use Rails' `enum` field myself (it only supports integer values in the database)

That's not really true, you can use strings with it

**Comment by eLod** [comment] 2020-02-07 05:59
@klyonrad oh yes, i haven't realised it, that said the docs specifically mention it is designed for integers (so the implementation can change). anyways i feel using the helper for associations (e.g. where the enum comes from another table) is still a valid use-case.

**Comment by composerinteralia** [comment] 2020-02-07 15:05
> Will this be picked up for reviewing/merging in this year? Is there anything that blocks it?

I do plan to get this feature merged in. The only thing blocking it is a lack of time to review. I will try my best to take a look this month.

**Closed** 2020-05-01 21:50 UTC
Labels: attached PR
